### ISSUE TITLE
Allow websockets annotation doesn't appear to work

### ISSUE THREAD

**Issue by gaurdro** [pomerium/ingress-controller#1032]
## What happened?

Allow websockets annotation does not seem to work when added to an ingress. 

## What did you expect to happen?

websockets work. 
## How'd it happen?

1. kubectl apply configuration below.  
2. visit configured URL 
3. get error about websockets

## What's your environment like?

- docker desktop k8s cluster on mac
- pomerium 0.26.2 via kubectl apply -k github.com/pomerium/ingress-controller/config/default\?ref=v0.26.2 and following quickstart guide

## What's your config.yaml?

```app-manifest.yaml
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: gaurdro-dev
  labels:
    app: code-server
    service: code-server
spec:
  ports:
    - port: 8000
      targetPort: 8443
      name: http
  selector:
    app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: gaurdro-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - image: linuxserver/code-server
          imagePullPolicy: Always
          name: code-server
          ports:
            - containerPort: 8443
              protocol: TCP
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gaurdro-dev
  namespace: gaurdro-dev
  annotations:
    ingress.pomerium.io/allow_websockets: 'true'
    allow_websockets: 'true'
    ingress.pomerium.io/allowed_domains: |
      - pomerium.com
    ingress.pomerium.io/pass_identity_headers: 'true'
spec:
  ingressClassName: pomerium
  rules:
    - host: 'gaurdro-dev.localhost.pomerium.io'
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: code-server
                port:
                  number:  8000
```

## What did you see in the logs?

[requestlogs.txt](https://github.com/user-attachments/files/16981675/requestlogs.txt)

## Additional context

code-server has been demonstrated to work in standalone mode recently.

**Comment by calebdoxsey** [comment]
The ingress controller is creating the route with the option set. I will try running the code server using regular pomerium to see what's different.

**Comment by calebdoxsey** [comment]
It doesn't work with core pomerium either. It does work with older versions of code-server. I will try to find out when it broke.

**Comment by calebdoxsey** [comment]
It broke with https://github.com/coder/code-server/releases/tag/v4.10.1 . Setting:

```yaml
preserve_host_header: true
```

fixed it. This option is available in the ingress controller as:

```
metadata:
  name: code-server
  annotations:
    ingress.pomerium.io/preserve_host_header: "true"
```

**Comment by calebdoxsey** [comment]
Added https://github.com/pomerium/documentation/pull/1645.

Going to close this issue since adding the additional annotation fixed the problem.
