### ISSUE TITLE
default policy

### ISSUE THREAD

**Issue by wasaga** [pomerium/ingress-controller#109]
**Is your feature request related to a problem? Please describe.**

It may be beneficial to define a default policy that would be applied to an Pomerium-managed Ingress, in case one is not defined. 

**Describe the solution you'd like**

[`IngressClass`](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) supports referencing  a CRD for ingress controller customization. 

Prefer option 1 (`PomeriumConfiguration` CRD) from the list below. 

**Describe alternatives you've considered**

We have the following options depending on our appetite for customization: 

1. Introduce a `PomeriumConfiguration` CRD that would map to `Settings` protobuf with addition of `default_policy` field that would expose PPL, and allow customizing all standard parameters available there. The side benefit here is that we may greatly simplify Helm by deploying an empty Pomerium and configuring it in runtime using `PomeriumConfiguration` CRD. The advantage of CRDs is that you may attach status and events to it, accessible via `kubectl describe`. 
2. Just add a runtime configuration parameter `default_policy` that should be a JSON encoded PPL. This parameter would have to be passed via Helm chart, contributing to its complexity. 
3. Use standard `ConfigMap` as a key-value map and start gradually exposing global configuration parameters similar to option 1. The disadvantage here is that it would not be strongly typed. 

**Explain any additional use-cases**

- k8s ingress conformance tests that assume Ingresses do not require authentication
- default policy that i.e. establishes access just to corporate domain and/or groups using PPL.

**Additional context**

**Comment by travisgroth** [comment]
From discussion - (2) seems like the right choice for now.

**Comment by wasaga** [comment]
it doesn't seem default policy would help unblock conformance tests.
