### ISSUE TITLE
Regex Paths `^` Prefix and `$` Suffix shouldn't be mandatory or not needed at all

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/ingress-controller#117]
**Is your feature request related to a problem? Please describe.**

As mentioned in the comment https://github.com/pomerium/ingress-controller/pull/100#issuecomment-1004892693 using a third party Ingress Controller like Nginx and the Pomerium Ingress Controller in an operator mode, using path regexes with the prefix `^` won't be allowed. Also worth mentioning that Nginx is automatically adding that prefix and the `$` suffix to the routes. Users need only to define the absolute path e.g. `/admin/.*` (https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/#regular-expression-support)

**Describe the solution you'd like**
In my view there could be two possible solutions to address this shortcoming:
1. The `^` prefix and `$` suffix could be optional; basically the controller adds them if they don't exist in the path as the first and last character respectively
2. Defining the `^` prefix and `$` suffix could be forbidden in the sense that users MUST only define the absolute path like what Nginx is doing; the Controller will handle adding them to these paths in its logic always

**Describe alternatives you've considered**
N.A.

**Explain any additional use-cases**
N.A.

**Additional context**
N.A.

**Comment by sherifkayad** [comment]
@wasaga for your reference and as per my comment on #100

**Comment by wasaga** [comment]
the regex syntax is currently consistent with core product https://www.pomerium.com/reference/#regex - note the path must be matched in full by the regex, or there would be no match, this is done for security purposes. 

in general it's not recommended to introduce an additional heuristic around regular expressions.

**Comment by sherifkayad** [comment]
@wasaga yeah but this basically means that users of Nginx won't be able to use the Regex functionality with Pomerium in an Operator mode. Any thoughts?

**Comment by sherifkayad** [comment]
One other possible idea maybe would be letting the path regex be passed via an annotation like the older Operator did e.g. `ingress.pomerium.io/regex`

**Comment by wasaga** [comment]
the advantage of having regex accepted in path directly is that you may have unlimited amounts of paths. however, you may only have single annotation per ingress object.

**Comment by sherifkayad** [comment]
@wasaga in that case what would you suggest to tackle the problem at hand? .. I really appreciate how Pomerium in combination with Nginx work perfectly for our case and I would love to keep using that .. so I am definitely open for suggestions how to proceed.

**Comment by sherifkayad** [comment]
> the advantage of having regex accepted in path directly is that you may have unlimited amounts of paths. however, you may only have single annotation per ingress object.

BTW if the solution would be doing it with an annotation, different regexes could be passed using comma (`,`) or something as a separator .. just thinking out loud here

**Comment by travisgroth** [comment]
Hi @sherifkayad,

While we want to continue to support forward-auth where reasonable, there will always be limits to functionality when trying to cooperate with a third party proxy; especially when sharing an API that isn't intended to be shared.  In this case, our syntax isn't compatible since the regex format of an ingress is implementation specific.  Even if we matched nginx 1:1, it wouldn't work with Traefik.  I think the `paths` based syntax is, as @wasaga points out, a good approach.

You can probably work around this particular case by configuring the routes in Pomerium's config directly and using an alternate ingress class that Pomerium Ingress isn't watching.

You could alternately leverage Pomerium's Ingress Controller for these endpoints, which would be our recommendation.

**Comment by sherifkayad** [comment]
> While we want to continue to support forward-auth where reasonable, there will always be limits to functionality when trying to cooperate with a third party proxy; especially when sharing an API that isn't intended to be shared

@travisgroth I agree 100% with that .. however, I really believe that this one can be solved by enabling an annotation that can override the path in the `paths` section. So basically by default the Pomerium Ingress Controller fetches the Regexes from the Ingress paths, however, the user can be given the ability to override those with an annotation to address the differences that come with each vendor e.g. Nginx, Traefik, .. etc.


> You can probably work around this particular case by configuring the routes in Pomerium's config directly and using an alternate ingress class that Pomerium Ingress isn't watching.

Unfortunately that's not as easy as it sounds because we have hundreds of microservices; where each service needs to specify some endpoints (with regexes most of the times) that need to be protected and not left widely open to everyone. That's why an "Operator" Mode / Pattern is a must have for us.

I would really appreciate if you guys can put some more thought into that and enable a Regexes override logic with an annotation. Here I would say for simplicity one annotation value (without comas or anything) could get us going .. again similar to the good old `ingress.pomerium.io/regex` of the deprecated Pomerium Operator.

**Comment by sherifkayad** [comment]
@travisgroth any thoughts on my comment above?

**Comment by wasaga** [comment]
addressed in https://github.com/pomerium/ingress-controller/issues/117

**Comment by sherifkayad** [comment]
@wasaga with the change introduced in https://github.com/pomerium/pomerium/pull/2966 would there by any todo for the Ingress (of course aside from upgrading the Pomerium version) needs to be done to address my issue here?

**Comment by wasaga** [comment]
@sherifkayad should get into next minor release of both core and ingress-controller.

**Comment by sherifkayad** [comment]
@wasaga @travisgroth could you please release a new version of the controller that has the fix from the core? I saw that version 0.16.2 of the core was issued a few days ago.

Thanks in advance.

**Comment by travisgroth** [comment]
New release is out https://github.com/pomerium/ingress-controller/releases/tag/v0.16.1

**Comment by sherifkayad** [comment]
@travisgroth @wasaga Unfortunately the fix isn't working as expected 😢 .. There's an edge case that I documented on the ticket #135 .. would be great if you guys can have a look at that.
