### ISSUE TITLE
No TLS definition on an Ingress object causes errors in the logs

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/ingress-controller#177]
## What happened?
It seems like the Ingress Controller is expecting that each watched Ingress object is defining a TLS cert (via a secret) and it wants to read the secret and validate it (continously at reconciling).

In my view this behavior should be configurable; basically one SHOULD be able to turn it off e.g. when having a TLS termination at the L7 Loadbalancer level not on the Ingress / Ingress Controller level.

Worth mentioning I am already running Pomerium with the `insecure` flag to basically let things run with TLS.

## What did you expect to happen?
No errors thrown in the logs if the ingress objects don't define a TLS secret

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): Ingress Controller 0.17.0 with the latest Pomerium 0.17.1
- Server Operating System/Architecture/Cloud: AWS / Helm

## What's your config.yaml?
Not relevant I guess ..

## What did you see in the logs?

```logs
{"level":"error","ts":1649229679.6618586,"logger":"controller.ingress","msg":"Reconciler error","reconciler group":"networking.k8s.io","reconciler kind":"Ingress","name":"my-secure-ingress","namespace":"my-namespace","error":"fetch ingress related resources: tls: spec.TLS.secretName was empty, could not get default cert from ingressClass: default cert secret name: annotation ingress.pomerium.io/default-cert-secret is missing"}
```

**Comment by wasaga** [comment]
@sherifkayad yes we introduced `default-cert` on the controller level and added an additional check for the `tls` section of the `Ingress`. As Pomerium is not a general purpose ingress controller, and is designed to only allow authenticated and authorized access over HTTPS, the expectation is that, in a kubernetes environment, you either have a catch-all controller level default cert or you specify a secret with a particular TLS cert in the Ingress. 

We would like to better understand your environment and the underlying requirements and use cases why you must have a TLS load balancer in front of the Pomerium in a k8s environment.

**Comment by sherifkayad** [comment]
@wasaga my use case is as described above is not performing any TLS termination on the Ingress level rather at the load balancer level e.g. for a company wide certificate that we use with internal domains and applied as a wild card certificate for anything under my-domain.com e.g. servicex.mydomain.com.

We are running Pomerium in an insecure mode and in mu view such enforcement of using a TLS certificate is wrong/ contradicting with the fact that you can run Pomerium / the Pomerium Ingress controller behind a load balancer that can do the TLS termination.

It doesn't matter whether you use Pomerium as a fully fledged Ingress Controller or not; at the end it must be possible to specify where the TLS termination takes place if that's on the Ingress level or rather at the cloud load balancer on top of it! .. That is the behavior in almost all Ingress Controllers and I don't really get the idea behind enforcing TLS termination by Pomerium or the Pomerium Ingress Controller.

**Comment by wasaga** [comment]
@sherifkayad thank you for clarification. 

may I ask few more questions so that we would better understand that deployment scenario. 

- do you currently use TLS or HTTPS load balancer with a company-wide certificate? 
- as described in [our documentation](https://www.pomerium.com/reference/#insecure-server), we recommend using internal certificates between the load balancer and Pomerium as an alternative for the `insecure` mode. Does your load balancer support it? Are there any limitations wrt custom CA or self-signed certs? 

We understand that regular ingress controllers support an insecure mode, as they're designed to serve any kind of content. Pomerium, to the contrary, was designed with end to end encryption in mind. 

As far as supporting an `insecure` mode that you may set for the core Pomerium on the ingress controller side, we may create an additional annotation for the controller level, i.e. `insecure`, in addition to recently added ability to add a default certificate for all ingresses that Pomerium Ingress Controller manages that do not specify TLS secret itself - see [`defaultCertSecret`](https://www.pomerium.com/docs/k8s/helm.html).

**Comment by sherifkayad** [comment]
@wasaga to your questions:
- HTTPS load balancer which is performing the offloading. Traffic would flow using insecure HTTP afterwards in our cluster; in other words services communicate with each other using insecure protocols. We don't believe that we need any TLS communication nor mTLS auth at the moment
- Second point:
  - I am not sure the Load Balancer supports that / we want to do that to be honest. We are using an AWS LB
  - Yes for some of our internal / lab environments we are using self-signed certificates
  - We have a setup where Pomerium is not directly behind the load balancer; rather behind Nginx which is our main Ingress Controller. So that could be a limitation

**Comment by sherifkayad** [comment]
@wasaga any updates on this one?

**Comment by wasaga** [comment]
@sherifkayad we are discussing internally how to best approach this and some other related issues in a consistent manner, we should have an update soon.

**Comment by sherifkayad** [comment]
@wasaga great news! Keep me posted.

**Comment by sherifkayad** [comment]
@wasaga @desimone any updates here? It's becoming quite critical for us 😢

**Comment by desimone** [comment]
Hi @sherifkayad  -- We plan to support insecure mode behavior in order to be consistent with Pomerium core's. We plan to include it in our next minor release.

**Comment by sherifkayad** [comment]
@desimone is there a time plan already for approximately when this minor release would be issued?
