### ISSUE TITLE
Support KubernetesServiceAccountTokenFile in Ingress Annotation

### ISSUE THREAD

**Issue by WojoInc** [pomerium/ingress-controller#188]
**Is your feature request related to a problem? Please describe.**

Currently the example for securing the [Kubernetes Dashboard](https://www.pomerium.com/guides/kubernetes-dashboard.html) does not work when using the Pomerium ingress controller. It can be made to work by specifying `ingress.pomerium.io/kubernetes_service_account_token` as an annotation (would require adding it as a supported annotation); however this exposes said token in plaintext in the rendered yaml.

**Describe the solution you'd like**

Support the KubernetesServiceAccountTokenFile Route option as an Ingress annotation.

**Describe alternatives you've considered**

I was in the process of migrating to the Ingress controller and moving all Route definitions out of the config file.
Continuing to specify a route for the Kubernetes Dashboard within the config file works for now.

**Explain any additional use-cases**

Any other applications which leverage Kubernetes RBAC.

**Additional context**

Will submit a PR for this shortly, as it requires updating the `config.proto` in pomerium/pomerium, as well as adding support for the annotation in this project as well.

**Comment by wasaga** [comment]
Thank you @WojoInc for pinpointing that issue and PRs. 

As configuration is replicated across various Pomerium components, we cannot rely on `_file` configuration fields, and they exist for historical reasons only. 

We discussed the issue you raised and would like to generalize it into a more generic solution to handling secrets in the `Ingress` resource, similar to referencing TLS secrets via annotations. Please see #190 for details.

**Comment by wasaga** [comment]
closed by https://github.com/pomerium/ingress-controller/pull/198
