### ISSUE TITLE
Secret Support

### ISSUE THREAD

**Issue by wasaga** [pomerium/ingress-controller#190]
**Is your feature request related to a problem? Please describe.**

Currently additional Pomerium route parameter such as headers, certs, tokens etc must be set via plaintext annotations to the `Ingress` resource, and it is impossible to link it with a k8s `Secret`. 

We already support referencing secrets for annotations related to custom TLS data, that would extend it to other fields with potentially sensitive data. 

**Describe the solution you'd like**

Add `_secret` suffix support to the following annotations, that would allow them to reference a secret that contains the required data, instead of providing the data in the plaintext form. 

- `set_request_headers`
- `set_response_headers`
- `kubernetes_service_account_token`

**Describe alternatives you've considered**

**Explain any additional use-cases**

**Additional context**

Related to 
- https://github.com/pomerium/ingress-controller/issues/188
- https://github.com/pomerium/ingress-controller/issues/86

**Comment by desimone** [comment]
Is this complete?
