### ISSUE TITLE
Ingress fails upsert with k8s token annotation

### ISSUE THREAD

**Issue by WojoInc** [pomerium/ingress-controller#205]
## What happened?

Attempting to add an Ingress resource using the new `ingress.pomerium.io/kubernetes_service_account_token_secret` annotation leads to errors on upsert, and pomerium fails to apply any changes.

## What did you expect to happen?

Ingress to be updated with the new annotation, and k8s service account token to be populated from provided secret.

## How'd it happen?

1. Created opaque secret `dashboard-impersonate` with a `token` key, and corresponding value
2. Added the annotation: `ingress.pomerium.io/kubernetes_service_account_token_secret: dashboard-impersonate`
3. Attempted to load kubernetes dashboard in browser, received 404 response
4. Checked logs for ingress-controller, got the error provided below:

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.17.3
- Server Operating System/Architecture/Cloud: Ubuntu/adm64/k8s

## What's your config.yaml?

```config.yaml
autocert: false
dns_lookup_family: V4_ONLY
address: :443
grpc_address: :443
certificate_authority_file: "/pomerium/ca/ca.crt"
certificates:
authenticate_service_url: https://auth.xxxx.xxx
authorize_service_url: https://pomerium-authorize.xxx
databroker_service_url: https://pomerium-databroker.xxx
idp_provider: okta
idp_scopes: 
idp_provider_url: 
forward_auth_url: https://pomerium-proxy.xxx
idp_client_id: REPLACE_ME
idp_client_secret: REPLACE_ME    
routes:

```

## What did you see in the logs?

```logs
{"level":"error","ts":1651961471.9970489,"logger":"controller.ingress","msg":"Reconciler error","reconciler group":"networking.k8s.io","reconciler kind":"Ingress","name":"kubernetes-dashboard","namespace":"monitoring","error":"upsert: updating certs: secret=dashboard-impersonate, expected type kubernetes.io/tls, got Opaque"}
```

## Additional context

Appears to be due to `*IngressConfig.ParseTLSCerts` assuming that anything in the `ic.Secrets` map is a TLS cert that it needs to process https://github.com/pomerium/ingress-controller/blob/9d6da366b8766cf81e96484d4b78e744cec27f42/model/ingress_config.go#L143-L147

**Comment by wasaga** [comment]
@WojoInc thank you for feedback, agree we should just skip a non-TLS certs here, but that check would have to be migrated up the chain; I'll prep a fix with integration test shortly.
