### ISSUE TITLE
move OPA validation to core

### ISSUE THREAD

**Issue by wasaga** [pomerium/ingress-controller#270]
The following code block causes `ingress-controller` have OPA as a direct dependency. 
We should move this function into core, so that OPA versioning would be dictated by core Pomerium, and not bumped independently. 

https://github.com/pomerium/ingress-controller/blob/fa5a1a3ef9fb29812beafa7ffa77163ced59d864/pomerium/ingress_annotations.go#L192-L205

**Comment by calebdoxsey** [comment]
Open source does not use these methods. I don't understand why we would add code to the open source that's only used by the ingress controller.
