### ISSUE TITLE
quick-start is wrong

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/ingress-controller#296]
## What happened?

Tried following the quick start on the ingress controller.

This gives a 404: 

```bash
kubectl apply -f https://raw.githubusercontent.com/pomerium/ingress-controller/main/deploy
```

Applying the IdP gives error: 

```
resource mapping not found for name: "global" namespace: "" from "./settings.yaml": no matches for kind "Settings" in version "[ingress.pomerium.io/v1](http://ingress.pomerium.io/v1)"
```

## What did you expect to happen?

To have instructions that yield a functioning ingress controller.

**Comment by wasaga** [comment]
quickstart: https://github.com/pomerium/documentation/pull/67/files
it looks like you're following the `README.md` in this repo which is outdated and is waiting for the following PR to be updated. https://github.com/pomerium/ingress-controller/pull/294
