### ISSUE TITLE
Add support for jwt_claims_headers configuration options

### ISSUE THREAD

**Issue by tombotch** [pomerium/ingress-controller#368]
**Is your feature request related to a problem? Please describe.**

I have an application that uses the X-Pomerium-Claim-* headers. However, there doesn't seem to be a way to enable these to be passed when using the ingress controller, as the configuration option needs to be set as per https://www.pomerium.com/docs/reference/jwt-claim-headers.

**Describe the solution you'd like**

I would like to be able to configure the full range of Pomerium configuration options that are available when not using the ingress controller. This could either be configured as additional options on the CRD, or as environment variables that are then passed through to Pomerium. Using the CRD would seem to be the better solution as that is how other global options are configured.

**Comment by wasaga** [comment]
global options are already set via CRD - please see https://www.pomerium.com/docs/k8s/reference

we currently do not have a CRD analog for the `Ingress`, thus `jwt_claims_headers` would have to be an annotation.
