### ISSUE TITLE
Support K8S Gateway API

### ISSUE THREAD

**Issue by paul-bormans** [pomerium/ingress-controller#463]
As also described in https://gateway-api.sigs.k8s.io/ an Ingress API (resource) isn't tied to a specific role, but instead contains configuration for both infrastructure, policies, frontend and backend. The new Gateway API solves this by splitting the ingress api into Gateway, Route, etc...

Today there is no support for the Gateway API in Pomerium and it would be nice to add it.

My question is whether there are plan / initiatives in this direction?

Paul

**Comment by desimone** [comment]
There are no immediate plans to implement the Gateway API but it is something we are investigating and encourage community feedback here as we investigate it. Thank you for the request @paul-bormans!

**Comment by rjbeers** [comment]
Happy to say we have support for Gateway API in 0.28. Learn more at https://docs.pomerium.com/docs/k8s/gateway-api. Let us know your feedback @paul-bormans !
