### ISSUE TITLE
Version v0.21.2 sets incorrect issuer in the `X-Pomerium-Jwt-Assertion` JWT token

### ISSUE THREAD

**Issue by logan-hcg** [pomerium/ingress-controller#573]
## What happened?

Using the ingress controller using the `v0.21.2` kustomization creates JWT assertions with the `iss` field set to `localhost:8443`.  This means that applications which use the `iss` to generate the JWKS endpoint (eg `verifier`) end up with the incorrect location `https://localhost:8443/.well-known/pomerium/jwks.json`.

Falling back to `v0.20.0` generates the correct `iss`.

**Comment by wasaga** [comment]
this problem is indeed present in 0.21 branch, however it is not present on `main`

**Comment by desimone** [comment]
Should be fixed in v0.22
