### ISSUE TITLE
Single Sign-out

### ISSUE THREAD

**Issue by phxavier2018** [pomerium/ingress-controller#581]
Good morning,

I am trying to implement the simple sign out, but I encounter a problem. Indeed, I use keycloak as a provider and if I understand the front-channel logout protocol the provider calls a url in an iframe, the problem is that pomerium sets the X-Frame-Options response header to SAMEORIGIN and therefore the browser blocks the response. How to modify this header in the pomerium authentication service? In the doc it is specified that we must not create an ingress for the authentication route, and if I understand the doc, the new way to modify the headers is an annotation in the ingress. Thanks

**Comment by calebdoxsey** [comment]
You can use the "Set Response Headers" option to disable these headers: https://www.pomerium.com/docs/reference/set-response-headers

```
set_response_headers:
  disable: true
```

This can be set the `ingress.pomerium.io/set_response_headers` annotation.
