### ISSUE TITLE
Pomerium v0.22.0 asking users for a certificate

### ISSUE THREAD

**Issue by cogoken** [pomerium/ingress-controller#623]
## What happened?

Users are being prompted to select a client certificate after upgrading to the v0.22.0 controller

## What did you expect to happen?

No certificate prompt, same behavior as v0.21.0

## How'd it happen?

Applied the deployment yaml for the v.0.22.0 branch.

## Additional context

I think probably related to https://github.com/pomerium/pomerium/issues/4150 and maybe fixed over there but would like to get the fix in the ingress controller as well.

**Comment by wasaga** [comment]
Fixed by https://github.com/pomerium/pomerium/pull/4151, will be in v0.22.1 ingress controller.
