### ISSUE TITLE
kubernetes service proxy bypass 

### ISSUE THREAD

**Issue by wasaga** [pomerium/ingress-controller#71]
**Is your feature request related to a problem? Please describe.**

Currently ingress controller defines a single upsteam for a service, in form of `http://service.namespace.svc.cluster.local`. 
The requests therefore are being proxied by the Kubernetes and distributed between the pods, which introduces an extra unnecessary network proxy. Also load balancing and health check options are largely meaningless. 

**Describe the solution you'd like**

Monitor k8s `Endpoints` resource for a service and update upstreams accordingly with each individual endpoint.

**Comment by travisgroth** [comment]
Interestingly, we do need a way to disable this when implemented.  In a service mesh deployment, we should actually use the kubernetes service so the mesh can do its thing.

**Comment by wasaga** [comment]
Is there a standard way to determine if you're running inside a service mesh?

**Comment by travisgroth** [comment]
I'm not aware of one.  Nginx implements this as a per-ingress annotation:  https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#service-upstream
