### ISSUE TITLE
Support ingress annotation "ingress.pomerium.io/jwt_claims_headers"

### ISSUE THREAD

**Issue by ThorbenJ** [pomerium/ingress-controller#730]
**Is your feature request related to a problem? Please describe.**

When used as a k8s ingress, I would like to be able to send JWT Claim headers, and not just the JWT Assertion header.
(Knowing that such headers cannot be verified)

**Describe the solution you'd like**

For https://www.pomerium.com/docs/reference/jwt-claim-headers to be supported as an ingress annotation "ingress.pomerium.io/jwt_claims_headers":

**Describe alternatives you've considered**

Another way to send claim info, such as group, name, email, etc to applications as HTTP headers

**Explain any additional use-cases**

To be able to support applications that support HTTP preauth (by setting headers) but cannot process JWT assertions, in closed environments where other components can be trusted

**Additional context**

The Pomerium Global k8s give the follow error:
```
  Warning  UpdateError  78s (x16 over 4m2s)  pomerium-ingress                         pomerium/echo-test-sso-ingress: parsing ingress: annotations: unknown ingress.pomerium.io/jwt_claims_headers
```

**Comment by wasaga** [comment]
this is not a per-route setting, and is set globally via the CRD [`jwtClaimsHeaders`](https://www.pomerium.com/docs/deploy/k8s/reference#spec) parameter

**Comment by ThorbenJ** [comment]
OK. So I'd have to set it such for all apps, just not the ones that need it.
