### ISSUE TITLE
(feat): watch for configmaps/secrets/crs for config change

### ISSUE THREAD

**Issue by lukasmrtvy** [pomerium/ingress-controller#85]
Would be nice to have feature for watching configmaps/secrets/CRs with special annotation for dynamic config change.

Examples:
vault ( bank-vault ) - https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/config-jwt-groups.yaml
argocd - https://argoproj.github.io/argo-cd/operator-manual/argocd-rbac-cm.yaml
prometheus-operator - its using CRs ..

**Comment by travisgroth** [comment]
After some consideration and the release of our [ingress controller](https://docs.pomerium.io/docs/k8s/ingress.html) I'm not sure that a custom resource type is needed.  

Even if you're using Traefik's `IngressRoute`, you should be able to also supply an Ingress that Traefik ignores and Pomerium processes in operator mode.  Please let us know if there's something we're missing about the requirements here.

**Comment by vixus0** [comment]
> you should be able to also supply an Ingress that Traefik ignores and Pomerium processes in operator mode. Please let us know if there's something we're missing about the requirements here.

Yeah that works if we can get Traefik to ignore the Ingress resources that get consumed by Pomerium. That should be doable by defining an IngressClass for the Pomerium controller and using `ingressClassName`, if I'm not mistaken.

**Comment by travisgroth** [comment]
👍 Yes that would be the idea.

Okay great.  Going to mark this closed then.
