### ISSUE TITLE
upgrade to k8s v30, controller-runtime v15

### ISSUE THREAD

**Issue by wasaga** [pomerium/ingress-controller#952]
**Is your feature request related to a problem? Please describe.**

in order to upgrade to K8S API v30, several breaking changes in the controller-runtime https://github.com/kubernetes-sigs/controller-runtime/pull/2783 have to be resolved

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by kralicky** [comment]
@ssveta7ak you should be able to test from main by installing with `kubectl apply -k github.com/pomerium/ingress-controller/config/default\?ref=main`

**Comment by ssveta7ak** [comment]
Fixed.
