### ISSUE TITLE
Ingress Paths with Regex don't work

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/ingress-controller#96]
## What happened?
Again on a migration path from the Operator to the Controller (related to the discussion we had in #94), it seems like the new Ingress Controller doesn't support Ingresses with regex paths nor it allows defining the good old annotation `ingress.pomerium.io/regex` to force Pomerium to interpret the path defined in the Ingress as Regex.

With a regex path in the Ingress e.g. `/.*/admin`, Pomerium literally expects `.*` to be provided in the URL and doesn't consider e.g. `/site1/admin` as a match to the route. The reason is obvious there's no way to instruct Pomerium to treat that path as a regex!

My Ingress definition look like:
```base-secure-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-secure-ingress
  labels:
    app: demo
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.mydomain.com/verify?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.mydomain.com?/uri=https://$host$request_uri"
    ingress.pomerium.io/allow_any_authenticated_user: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo
            port:
              number: 8080
```

```overlay-secure-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overlay-secure-ingress
  labels:
    app: demo
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.mydomain.com/verify?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.mydomain.com?/uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/use-regex: "true"
    ingress.pomerium.io/allowed_idp_claims: '{"groups": ["Team X", "Team Y"]}'
    # ingress.pomerium.io/regex: "^(?i).*/admin.*$" ==> not allowed anymore!
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mydomain.com
    http:
      paths:
      - path: /.*/admin
        pathType: Prefix
        backend:
          service:
            name: demo
            port:
              number: 8080
```

## What did you expect to happen?
Working with additional paths (including Regex paths) should authorize users as well e.g. `/something/admin` should authorize everyone who's in the `Team X` or `Team Y` IDP groups.

## How'd it happen?

- Hitting => https://demo.mydomain.com/.*/admin works!
- Hitting => https://demo.mydomain.com/something/admin doesn't authorize the user

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.15.7 // Ingress Controller version: 0.15.2 // Helm chart version: 25.0.3
- Server Operating System/Architecture/Cloud: AWS EKS 1.21

## What's your config.yaml?

```config.yaml
autocert: false
dns_lookup_family: V4_ONLY
address: :80
grpc_address: :80
authenticate_service_url: https://pomerium.mydomain.com
authorize_service_url: http://pomerium-authorize.pomerium.svc.cluster.local
databroker_service_url: http://pomerium-databroker.pomerium.svc.cluster.local
idp_provider: oidc
idp_scopes: [openid profile email groups offline_access]
idp_provider_url: https://idptest.emob.eu-central-1.internal.innogy.com
insecure_server: true
grpc_insecure: true

databroker_storage_connection_string: rediss://:password@redis-master.amazonaws.com
databroker_storage_tls_skip_verify: true
databroker_storage_type: redis
forward_auth_url: https://forwardauth.mydomain.com
cookie_secret: secret
shared_secret: secret
idp_client_id: secret
idp_client_secret: secret
idp_service_account: pomerium-authenticate
databroker_storage_tls_skip_verify: true    
routes:
  - allow_any_authenticated_user: true
    allow_spdy: true
    allow_websockets: true
    from: https://dashboard.mydomain.com
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    to: http://kubernetes-dashboard.kube-system.svc:443
  - allow_any_authenticated_user: true
    allow_spdy: true
    allow_websockets: true
    from: https://kubernetes.mydomain.com
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_skip_verify: true
    to: https://kubernetes.default.svc
```

## What did you see in the logs?
Nothing interesting .. The Ingress was accepted by the Pomerium Ingress Controller

## Additional context
Nothing further

**Comment by sherifkayad** [comment]
@travisgroth I see you added the label `NeedsDiscussion` .. is there anything I can help with / clarify?

**Comment by travisgroth** [comment]
> @travisgroth I see you added the label `NeedsDiscussion` .. is there anything I can help with / clarify?

Not currently.  That is for our team to discuss internally.

**Comment by wasaga** [comment]
I think we can add an annotation `ingress.pomerium.io/path-regex` which will make any path with `pathType: ImplementationSpecific` treated as regex path.

**Comment by sherifkayad** [comment]
@wasaga well, that would be great 👍 .. I like this idea a lot.

**Comment by drewp** [comment]
For those who landed on this page, the final  annotation spelling is path_regex, like this:
```
metadata:
  annotations:
    ingress.pomerium.io/path_regex: "true"
spec:
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
```
